name: Build and Deploy

on:
    push:
        branches:
            - main

#Disable all permissions on global scope, each permission will be assigned at the job level scope
permissions: {}

jobs:
    build:
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
          - name: Checkout main branch
            uses: actions/checkout@v4
          - name: Build
            run: make
    deploy:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Deploy to gh-pages
          uses: peaceiris/actions-gh-pages@v4
          with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./output
