name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run make
        run: make

      - name: Commit changes
        run: |
          cd output
          git init
          git switch -c gh-pages
          git remote add repo https://github.com/intel/ethernet-linux
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Add generated index.html"
          
      - name: Push to gh-pages branch
        run: |
          git push repo gh-pages
